permalink: /:year:month:day/:title
url: https://edenwuyifan.github.io
baseurl: ""

# variables
name: Eden's Personal Site
description: Win98-Eden
google_verification: null
mermaid: true


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "_posts/2017-09-16-markdown-test-page.md"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

plugins:
  - jemoji